name: quiz_app
services:
  nest-app:
    build:
      context: .
    image: ${DOCKER_IMAGE:-graff012/quiz-app:latest}
    environment:
      - DATABASE_URL=${DATABASE_DOCKER_URL}
      - JWT_KEY=${JWT_SECRET}
      - PORT=4000
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - '8080:4000'
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:17.5
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    env_file:
      - .env
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
  my_volumes:
